/**
 * Data Source Configuration
 * This file is auto-generated by GitHub Actions during deployment
 * DO NOT EDIT MANUALLY
 *
 * The repository information is injected during the CI/CD build process
 * to enable fetching data from the data branch
 */

const DATA_CONFIG = {
    /**
     * GitHub repository owner (username)
     * This will be replaced during GitHub Actions workflow execution
     */
    repoOwner: 'topomat12138',

    /**
     * GitHub repository name
     * This will be replaced during GitHub Actions workflow execution
     */
    repoName: 'daily-arXiv-ai-enhanced',

    /**
     * Data branch name
     * Default: 'data'
     */
    dataBranch: 'data',

    /**
     * Get the base URL for raw GitHub content from data branch
     * @returns {string} Base URL for raw GitHub content
     */
    getDataBaseUrl: function() {
        return `https://raw.githubusercontent.com/${this.repoOwner}/${this.repoName}/${this.dataBranch}`;
    },

    /**
     * Get the full URL for a data file
     * @param {string} filePath - Relative path to the data file (e.g., 'data/2025-01-01.jsonl')
     * @returns {string} Full URL to the data file
     */
    getDataUrl: function(filePath) {
        return `${this.getDataBaseUrl()}/${filePath}`;
    },

    /**
     * Get the configured repository URL.
     * @returns {string} GitHub repository URL
     */
    getRepositoryUrl: function() {
        return `https://github.com/${this.repoOwner}/${this.repoName}`;
    },

    /**
     * Get the configured repository's GitHub API URL.
     * @returns {string} GitHub repository API URL
     */
    getRepositoryApiUrl: function() {
        return `https://api.github.com/repos/${this.repoOwner}/${this.repoName}`;
    },

    /**
     * Get the configured repository's issues URL.
     * @returns {string} GitHub issues URL
     */
    getIssuesUrl: function() {
        return `${this.getRepositoryUrl()}/issues`;
    },

    /**
     * Assign configured repository URLs to marked page links.
     * @param {Document|Element} root - Root node containing repository links
     */
    applyRepositoryLinks: function(root) {
        const linkRoot = root || document;
        linkRoot.querySelectorAll('[data-repository-link]').forEach(link => {
            link.href = link.dataset.repositoryLink === 'issues'
                ? this.getIssuesUrl()
                : this.getRepositoryUrl();
        });
    }
};

if (typeof document !== 'undefined') {
    document.addEventListener('DOMContentLoaded', () => DATA_CONFIG.applyRepositoryLinks());
}
